<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php $_helper = $this->helper('WeltPixel\LazyLoading\Helper\Data');  ?>
<img class="photo image lazy"
     <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
     src="<?php /* @escapeNotVerified */ echo $_helper->getImageLoader(); ?>"
     data-original="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>" />